from win32api import GetSystemMetrics
from game.fileLoader import *

MISION=""
SCREENWIDTH = 950
SCREENHEIGHT = 700
GAME=""
GAME_DISPLAY=""
MENU_IMG=""
CHAR_IMG=""
TRIV_IMG=""
MENU_AUD=""
CHARS=[]
SELECTED_CHAR=""
DIFICULTAD=""
IMAGES=None
SOUNDS=None
STATE="MENU"
BANDO=""
LIVES=""
TIE_COUNTER=0